/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const GoalId = IDL.Nat;
export const GoalStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Goal = IDL.Record({
  'id' : GoalId,
  'status' : GoalStatus,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Opt(IDL.Text),
  'updatedAt' : Time,
  'progress' : IDL.Nat,
  'targetDate' : IDL.Opt(Time),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGoal' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Time)],
      [GoalId],
      [],
    ),
  'deleteGoal' : IDL.Func([GoalId], [], []),
  'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoal' : IDL.Func([GoalId], [Goal], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGoal' : IDL.Func(
      [GoalId, IDL.Text, IDL.Opt(IDL.Text), GoalStatus, IDL.Opt(Time), IDL.Nat],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const GoalId = IDL.Nat;
  const GoalStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Goal = IDL.Record({
    'id' : GoalId,
    'status' : GoalStatus,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Opt(IDL.Text),
    'updatedAt' : Time,
    'progress' : IDL.Nat,
    'targetDate' : IDL.Opt(Time),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGoal' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Time)],
        [GoalId],
        [],
      ),
    'deleteGoal' : IDL.Func([GoalId], [], []),
    'getAllGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoal' : IDL.Func([GoalId], [Goal], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGoal' : IDL.Func(
        [
          GoalId,
          IDL.Text,
          IDL.Opt(IDL.Text),
          GoalStatus,
          IDL.Opt(Time),
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };