/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Goal {
  'id' : GoalId,
  'status' : GoalStatus,
  'title' : string,
  'createdAt' : Time,
  'description' : [] | [string],
  'updatedAt' : Time,
  'progress' : bigint,
  'targetDate' : [] | [Time],
}
export type GoalId = bigint;
export type GoalStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createGoal' : ActorMethod<[string, [] | [string], [] | [Time]], GoalId>,
  'deleteGoal' : ActorMethod<[GoalId], undefined>,
  'getAllGoals' : ActorMethod<[], Array<Goal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoal' : ActorMethod<[GoalId], Goal>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGoal' : ActorMethod<
    [GoalId, string, [] | [string], GoalStatus, [] | [Time], bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];